name: CoolFluentHelpers NuGet Deploy
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x.x'  # Replace x with the desired version number

    - name: Get Release Tag Version
      id: get_release_version
      run: echo "::set-output name=version::${GITHUB_REF##*/}"

    - name: Update Project Version
      run: |
        sed -i "s|<PackageTags>.*</PackageTags>|<PackageTags>${{ steps.get_release_version.outputs.version }}</PackageTags>|" $(find . -type f -iname 'CoolFluentHelpers.csproj')

    - name: Build and pack
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release

    - name: Find NuGet package
      id: find_package
      run: |
        find . -name '*.nupkg' -print0 | xargs -0 echo "::set-output name=package_path::"

    - name: Publish NuGet package
      run: |
        dotnet nuget push ${{ steps.find_package.outputs.package_path }} --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json